# Generated by Django 3.2.3 on 2021-05-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_avatar_url',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
    ]
