# Generated by Django 3.2.3 on 2021-05-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('description', models.TextField(max_length=255, verbose_name='팀 설명')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀들',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, null=True, verbose_name='별명')),
                ('is_admin', models.BooleanField(default=False, verbose_name='팀 관리자 여부')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='teams.team', verbose_name='팀')),
            ],
            options={
                'verbose_name': '구성원',
                'verbose_name_plural': '구성원들',
                'ordering': ['team', 'nickname'],
            },
        ),
    ]
