# Generated by Django 3.2.3 on 2021-05-23 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id'], 'verbose_name': '팀', 'verbose_name_plural': '팀들'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['team', 'nickname'], 'verbose_name': '구성원', 'verbose_name_plural': '구성원들'},
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(max_length=255, verbose_name='팀 설명'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='teams.TeamMember', to=settings.AUTH_USER_MODEL, verbose_name='팀 구성원'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='팀 관리자 여부'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='nickname',
            field=models.CharField(max_length=50, null=True, verbose_name='별명'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='teams.team', verbose_name='팀'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
